### ISSUE TITLE
https://github.com/coinbase/cbpay-js/issues/141#issuecomment-1616258967_

### ISSUE THREAD

**Issue by SocialGoo** [coinbase/cbpay-js#153]
@Hoodresponse tome....
/
``` rl)`

_Originally posted by @Billiej88 in https://github.com/coinbase/cbpay-js/issues/141#issuecomment-1616258967_

**Comment by Billiej88** [comment]
what is this for

**Comment by Taylorman3** [comment]
God Bless all of You
