### ISSUE TITLE
> > > > Continuehttps://www.capitalone.com/legal/disclosureshttps://core.telegram.org/file/811140227/2/ZTXUngAbELM.193805/ba6aa233d1d4206207

### ISSUE THREAD

**Issue by Billiej88** [coinbase/cbpay-js#156]
> > > > Continuehttps://www.capitalone.com/legal/disclosureshttps://core.telegram.org/file/811140227/2/ZTXUngAbELM.193805/ba6aa233d1d4206207

_Originally posted by @Billiej88 in https://github.com/coinbase/cbpay-js/issues/141#issuecomment-1638720072_

**Comment by Billiej88** [comment]
> ```
>           > > > > Continuehttps://www.capitalone.com/legal/disclosureshttps://core.telegram.org/file/811140227/2/ZTXUngAbELM.193805/ba6aa233d1d4206207
> ```
> 
> _Originally posted by @Billiej88 in [#141 (comment)](https://github.com/coinbase/cbpay-js/issues/141#issuecomment-1638720072)_

**Comment by Tarrexino** [comment]
Thanks 🙏🙏

**Comment by Billiej88** [comment]
> https://www.capitalone.com/legal/disclosureshttps://core.telegram.org/file/811140227/2/ZTXUngAbELM.193805/ba6aa233d1d4206207
