### ISSUE TITLE
1000000187 (750×1176)

### ISSUE THREAD

**Issue by Taylorman3** [coinbase/cbpay-js#167]
![chrome_qrcode_1692212859407.png](https://github.com/coinbase/cbpay-js/assets/138327228/eefce068-840d-4ded-b3af-83bf051e2c17)

**Comment by Billiej88** [comment]
> ![chrome_qrcode_1692212859407.png](https://user-images.githubusercontent.com/138327228/261253268-eefce068-840d-4ded-b3af-83bf051e2c17.png)

**Comment by Taylorman3** [comment]
Thank you for your email

**Comment by Taylorman3** [comment]
What is this

**Comment by Taylorman3** [comment]
> ![chrome_qrcode_1692212859407.png](https://github.com/coinbase/cbpay-js/assets/138327228/eefce068-840d-4ded-b3af-83bf051e2c17)
> 
>
