### ISSUE TITLE
coinbase / cbpay-js

### ISSUE THREAD

**Issue by derik1984** [coinbase/cbpay-js#175]
derik1984

**Comment by derik1984** [comment]
closed

**Comment by derik1984** [comment]
closed!??

**Comment by Kittenone6** [comment]
I have to apologize for not attending but I have been sick for the last 4 flipping years and everytime I think I'm going to get better I get sick again. Y'all have done an excellent work thank you. Hoping to get to work soon.

**Comment by Tarrexino** [comment]
You are welcome back

**Comment by Tarrexino** [comment]
Yes thanks
