### ISSUE TITLE
The react widget opens up a new tab without ever calling instance.open

### ISSUE THREAD

**Issue by scottwilson312** [coinbase/cbpay-js#203]
What would cause this?

**Comment by scottwilson312** [comment]
This only happens if I navigate back to a page with the coinbase pay button. I verified that I'm called destroy.

**Comment by scottwilson312** [comment]
I found a work around

**Comment by Hi2885** [comment]
Not finished

**Comment by tylerdmace** [comment]
@scottwilson312 May I ask what your work around was?
