### ISSUE TITLE
https://github.com/coinbase/cbpay-js/issues/253#issue-2203099228

### ISSUE THREAD

**Issue by katrkatcloud** [coinbase/cbpay-js#269]
https://github.com/coinbase/cbpay-js/issues/253#issue-2203099228

_Originally posted by @Billiej88 in https://github.com/coinbase/cbpay-js/issues/253#issuecomment-2016880282_

**Comment by katrkatcloud** [comment]
https://github.com/coinbase/cbpay-js/issues/253#issue-2203099228

**Comment by Billiej88** [comment]
> ```
>           https://github.com/coinbase/cbpay-js/issues/253#issue-2203099228
> ```
> 
> _Originally posted by @Billiej88 in [#253 (comment)](https://github.com/coinbase/cbpay-js/issues/253#issuecomment-2016880282)_
