### ISSUE TITLE
CommonJS build output uses invalid `import` syntax

### ISSUE THREAD

**Issue by cjthompson** [coinbase/cbpay-js#27]
# Description
The file `dist/chunk-BM7N7EVA.js` includes the line
```
import regeneratorRuntime from "regenerator-runtime";
```

When running in a commonJS environment, such as Jest, this results in the error:
```
import regeneratorRuntime from "regenerator-runtime";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

An additional error is that `package.json` does not include `regenerator-runtime` as a dependency.

# Solution
I found that this problem can be solved by changing the `target` option in `tsup.config.ts` to anything other than `es5`.

The invalid imports appear to be injected as part of the transpile step to es5.

I also don't understand why `splitting` is turned on in `tsup.config.ts`.  The output files without splitting are just 16KB.

**Comment by zack-winchell-cb** [comment]
Thanks for looking into this. We're currently wanting to keep the target pinned on es5, but we'll investigate other fixes on our end.

**Comment by Topi99** [comment]
Hi @zack-winchell-cb, any update about this?

**Comment by lachiet** [comment]
Hey @Topi99, does the [suggested fix](https://github.com/coinbase/cbpay-js/pull/28#issuecomment-1163784027) work for you?
