### ISSUE TITLE
Violation of Content Security Policy directive

### ISSUE THREAD

**Issue by prosenjitalpine** [coinbase/cbpay-js#41]
## Description
I tried to integrate this into my app. But seems like there is an error that tells me that an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'". Following is the entire error message -
```
Refused to frame 'https://pay.coinbase.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
```

## To Reproduce
Try running locally as instructed [here](https://github.com/coinbase/cbpay-js#basic-example). It also gives a similar kind of error when I deployed it to a host and run it using `HTTPS`. Usually, it shows the error during the page render and shows nothing when clicked on the "Buy with Coinbase" button.

## Expected behavior
It should show the payment inputs & other necessary options.

## Priority
P0, as the entire functionality is blocked because of this error.

## Screenshot
<img width="552" alt="Screenshot 2022-08-04 at 5 18 14 PM" src="https://user-images.githubusercontent.com/94828689/182823900-c083e03a-b571-4a92-9183-5ea4e3a2ff0f.png">

## Desktop
- OS: macOS Monterey
- Browser: Chrome, version 103.0.5060.134 (Official Build) (arm64)
- Resolution: 3024x1964
- Version: 1.0.2

**Comment by lachiet** [comment]
Hey @prosenjitalpine, that error happens when the domain for you appId is not added to the allowlist. From [the readme](https://github.com/coinbase/cbpay-js#documentation):

> See the [Coinbase Pay documentation](https://docs.cloud.coinbase.com/pay-sdk) for configuration options. Developers interested in using Coinbase Pay will need to contact the Coinbase Pay team to get their domains/extension IDs added to the Coinbase Pay allowlist. Please contact the Coinbase Pay team by filling [this form](https://www.coinbase.com/cloud/cloud-interest) and selecting “Coinbase Pay SDK” in the product dropdown menu.

**Comment by tjmabey** [comment]
So, is there no way to run this locally then?

**Comment by lachiet** [comment]
Hey @tjmabey, not without a valid appId at this point.

**Comment by lachiet** [comment]
@tjmabey there's a couple of options - you could use the generateOnRampUrl function to validate the config is correct for local dev, or you could potentially add an approved domain to local /hosts file and run localhost:3000 behind it. The second option might require creating a SSL cert to get past https requirements for the embedded iframe.

We're also looking into a way to allow easier localhost development so I'll keep you posted.
