### ISSUE TITLE
Errors when trying to use initOnRamp & generateOnRampURL

### ISSUE THREAD

**Issue by nickfujita** [coinbase/cbpay-js#47]
# initOnRamp
## Upon opening page where this module is integrated first error shows
![image](https://user-images.githubusercontent.com/6342442/186124950-6fafd0f3-639f-4a50-951a-11b511d9c963.png)

## Integrating with the following as shown in the example in readme, results in the errors shown below
```
  onExit: () => {
    console.log('onExit');
  },
  onSuccess: () => {
    console.log('onSuccess');
  },
  onEvent: (metadata) => {
    console.log('onEvent');
    console.log(metadata);
  },
```

![image](https://user-images.githubusercontent.com/6342442/186125802-51a51159-2a46-448c-98ff-8dcead7aa11c.png)
![image](https://user-images.githubusercontent.com/6342442/186125855-82996b5e-85ca-4e2a-b568-bf0fd1190c7e.png)
This page has the URL:
`https://pay.coinbase.com/buy/select-asset?appId=<my-app-id>&destinationWallets=%5B%7B%22address%22%3A%<wallet-address>%22%2C%22assets%22%3A%5B%22ETH%22%2C%22USDC%22%2C%22MATIC%22%5D%2C%22supportedNetworks%22%3A%5B%22ethereum%22%2C%22polygon%22%5D%7D%5D&experienceLoggedOut=embedded&onEvent=%28metadata%29+%3D%3E+%7B%0A++++++console.log%28%22onEvent%22%29%3B%0A++++++console.log%28metadata%29%3B%0A++++%7D&onExit=%28%29+%3D%3E+%7B%0A++++++console.log%28%22onExit%22%29%3B%0A++++%7D&onSuccess=%28%29+%3D%3E+%7B%0A++++++console.log%28%22onSuccess%22%29%3B%0A++++%7D`

## Always opens in a new tab, not embedded
- Running with the following code. On page load it proceeds to open a working pay widget in a new tab, but never actually embedded into the page
```
const instance = initOnRamp({
  appId,
  widgetParameters: {
    destinationWallets: [
      {
        address,
        assets: ['ETH', 'USDC', 'MATIC'],
        supportedNetworks: [
          'ethereum',
          'polygon',
        ],
      },
    ],
  },
  experienceLoggedIn: 'embedded',
  experienceLoggedOut: 'embedded',
});

instance.open();
```
Not sure if it's to do with any of the following errors in the console:
![image](https://user-images.githubusercontent.com/6342442/186127301-3ed35753-eb23-4153-9ad6-eb643bfcc56b.png)

# generateOnRampURL
- When using generateOnRampURL and placing into an iframe manually everything seems to be working fine, but the following errors are still in the console. I was able to make a purchase, but just wanted to make sure this was expected
![image](https://user-images.githubusercontent.com/6342442/186129990-5d2c853e-9118-4000-8146-ce974dbceef0.png)
- since only the manual iframe with the generated URL is working, would it be possible to add some documentation to https://docs.cloud.coinbase.com/pay-sdk/docs/integrating-pay on the `postMessage` api formats being used. I am able to parse out what I can from reading this repo, but how likely is that interface to change?

**Comment by lachiet** [comment]
Hey @nickfujita, thanks for the info. From the logs it looks like the pixel is failing to load which is why it's falling back to opening in a new tab. Do you see in network errors from the `https://pay.coinbase.com/embed`? 

It also looks like there's a bug in the generateOnRamp url function which results in that error screen.

**Comment by nickfujita** [comment]
Thanks for the response. the BD teams seems to have updated the allow listing or fixed something else, and the embed for the logged in experience is working. However, even when setting `experienceLoggedOut` to `embedded` it still opens in a popup instead.

When running with `debug:true`, it seems to know that embedded was requested, but still opens as popup instead
`[CBPAY] Opening experience {experience: 'embedded', isLoggedIn: false}`

**Comment by lachiet** [comment]
Hey @nickfujita , that's good to hear. This is expected behavior because user's can't login via an iframe on a third party website due to security reasons. What happens for the logged out flow is the popup will sign the user in, then automatically be dismissed. This should then trigger the logged in embedded experience as usual. Let me know if that's not the case or what scenario & platform you're trying to test.

**Comment by qqqq-collab** [comment]
> # initOnRamp
> ## Upon opening page where this module is integrated first error shows
> ![image](https://user-images.githubusercontent.com/6342442/186124950-6fafd0f3-639f-4a50-951a-11b511d9c963.png)
> 
> ## Integrating with the following as shown in the example in readme, results in the errors shown below
> ```
>   onExit: () => {
>     console.log('onExit');
>   },
>   onSuccess: () => {
>     console.log('onSuccess');
>   },
>   onEvent: (metadata) => {
>     console.log('onEvent');
>     console.log(metadata);
>   },
> ```
> 
> ![image](https://user-images.githubusercontent.com/6342442/186125802-51a51159-2a46-448c-98ff-8dcead7aa11c.png)
> ![image](https://user-images.githubusercontent.com/6342442/186125855-82996b5e-85ca-4e2a-b568-bf0fd1190c7e.png)
> This page has the URL:
> `https://pay.coinbase.com/buy/select-asset?appId=<my-app-id>&destinationWallets=%5B%7B%22address%22%3A%<wallet-address>%22%2C%22assets%22%3A%5B%22ETH%22%2C%22USDC%22%2C%22MATIC%22%5D%2C%22supportedNetworks%22%3A%5B%22ethereum%22%2C%22polygon%22%5D%7D%5D&experienceLoggedOut=embedded&onEvent=%28metadata%29+%3D%3E+%7B%0A++++++console.log%28%22onEvent%22%29%3B%0A++++++console.log%28metadata%29%3B%0A++++%7D&onExit=%28%29+%3D%3E+%7B%0A++++++console.log%28%22onExit%22%29%3B%0A++++%7D&onSuccess=%28%29+%3D%3E+%7B%0A++++++console.log%28%22onSuccess%22%29%3B%0A++++%7D`
> 
> ## Always opens in a new tab, not embedded
> - Running with the following code. On page load it proceeds to open a working pay widget in a new tab, but never actually embedded into the page
> ```
> const instance = initOnRamp({
>   appId,
>   widgetParameters: {
>     destinationWallets: [
>       {
>         address,
>         assets: ['ETH', 'USDC', 'MATIC'],
>         supportedNetworks: [
>           'ethereum',
>           'polygon',
>         ],
>       },
>     ],
>   },
>   experienceLoggedIn: 'embedded',
>   experienceLoggedOut: 'embedded',
> });
> 
> instance.open();
> ```
> Not sure if it's to do with any of the following errors in the console:
> ![image](https://user-images.githubusercontent.com/6342442/186127301-3ed35753-eb23-4153-9ad6-eb643bfcc56b.png)
> 
> # generateOnRampURL
> - When using generateOnRampURL and placing into an iframe manually everything seems to be working fine, but the following errors are still in the console. I was able to make a purchase, but just wanted to make sure this was expected
> ![image](https://user-images.githubusercontent.com/6342442/186129990-5d2c853e-9118-4000-8146-ce974dbceef0.png)
> - since only the manual iframe with the generated URL is working, would it be possible to add some documentation to https://docs.cloud.coinbase.com/pay-sdk/docs/integrating-pay on the `postMessage` api formats being used. I am able to parse out what I can from reading this repo, but how likely is that interface to change? 
>
