### ISSUE TITLE
Coinbase pay sdk doesn't work on React Native

### ISSUE THREAD

**Issue by kbihaniember** [coinbase/cbpay-js#75]
Hola guys,

When trying to integrate Coinbase pay with React Native, i'm getting an error when trying to `initOnRamp`:
`TypeError: window.addEventListener is not a function. (In 'window.addEventListener("message", onMessage)', 'window.addEventListener' is undefined)`

I tried to `generateOnRampURL` as well which threw this error:
`TypeError: Attempted to assign to readonly property.`

React native version being used: 0.63.5
Coinbase pay SDK version being used: 1.6.0

I followed the steps given [here](https://docs.cloud.coinbase.com/pay-sdk/docs/installing-sdk) to install the package

Is the sdk supported for React native (or mobile devices?)?
If yes, can you please help out with this error? If not, can you please point to the correct direction on how to use the sdk for mobile?

**Comment by Perronef5** [comment]
Dealing with the same issue

**Comment by Perronef5** [comment]
Hi @kbihaniember I came up with a solution and made a PR here to add additional documentation https://github.com/coinbase/cbpay-js/pull/76
