### ISSUE TITLE
SDk

### ISSUE THREAD

**Issue by felipedejes** [coinbase/cbpay-js#96]
- [ ] []()Npm install @coinbase/cbpay-js

The package is distributed as both ESModules and CommonJS. To use the CommonJS output, the regenerator-runtime package will also need to be installed:

With yarn:

yarn add regenerator-runtime

With npm:

npm install regenerator-runtime

import { initOnRamp } from '@coinbase/cbpay-js'; const options = { appId: 'your_app_id', widgetParameters: { destinationWallets: [{ address: '0xabc123', blockchains: ['ethereum', 'avalanche-c-chain'], }], }, closeOnExit: true, closeOnSuccess: true, embeddedContentStyles: { target: '#target-area', }, onExit: () => { alert('On Exit'); }, onSuccess: () => { alert('On Success'); }, onEvent: (metadata) => { console.log(metadata); }, } // Initialize the CB Pay instance let onrampInstance; const instance = initOnRamp(options, (error, instance) => { onrampInstance = instance; }); // Open the widget when the user clicks a button onrampInstance.open(); // When button unmounts destroy the instance onrampInstance.destroy();

import type { CBPayInstanceType, InitOnRampParams } from '@coinbase/cbpay-js'; import { initOnRamp } from '@coinbase/cbpay-js'; const PayWithCoinbaseButton: React.FC = () => { const [onrampInstance, setOnrampInstance] = useState<CBPayInstanceType | undefined>(); useEffect(() => { initOnRamp({ appId: 'your_app_id', widgetParameters: { destinationWallets: [ { address: '0xa', blockchains: ['ethereum', 'avalanche-c-chain'], }, ], }, onSuccess: () => { console.log('success'); }, onExit: () => { console.log('exit'); }, onEvent: (event) => { console.log('event', event); }, experienceLoggedIn: 'popup', experienceLoggedOut: 'popup', closeOnExit: true, closeOnSuccess: true, }, (_, instance) => { setOnrampInstance(instance); }); return () => { onrampInstance?.destroy(); }; }, []); const handleClick = () => { onrampInstance?.open(); }; return <Button onClick={handleClick} disabled={!onrampInstance}>Buy with Coinbase</Button>; };

>

**Comment by zack-winchell-cb** [comment]
This issue looks like it was opened in error.
